import { Question } from "../types";

export const level5Questions: Question[] = [
  {
    id: "l5_1",
    prompt: "Apa output dari kode berikut?",
    code: 'print("ya" if 5 > 3 else "tidak")',
    options: ["ya", "tidak", "True", "error"],
    expectedAnswers: ["ya"],
    hint: '5 lebih besar dari 3, jadi "ya"',
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_2",
    prompt: "Apa output dari kode berikut?",
    code: 'print("genap" if 4 % 2 == 0 else "ganjil")',
    options: ["genap", "ganjil", "True", "0"],
    expectedAnswers: ["genap"],
    hint: "4 habis dibagi 2",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_3",
    prompt: "Apa output dari kode berikut?",
    code: 'x = 10\nprint("besar" if x > 5 else "kecil")',
    options: ["besar", "kecil", "10", "True"],
    expectedAnswers: ["besar"],
    hint: '10 > 5 jadi "besar"',
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_4",
    prompt: "Apa hasil dari list comprehension berikut?",
    code: "[x for x in range(10) if x > 6]",
    options: ["[7, 8, 9]", "[6, 7, 8, 9]", "[7, 8, 9, 10]", "[8, 9]"],
    expectedAnswers: ["[7, 8, 9]"],
    hint: "Angka > 6 dari 0-9",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_5",
    prompt: "Apa output dari kode berikut?",
    code: "print(max(3, 7, 1))",
    options: ["7", "3", "1", "11"],
    expectedAnswers: ["7"],
    hint: "max() cari nilai terbesar",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_6",
    prompt: "Apa output dari kode berikut?",
    code: "print(min(5, 2, 8))",
    options: ["2", "5", "8", "15"],
    expectedAnswers: ["2"],
    hint: "min() cari nilai terkecil",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_7",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "bool(0)",
    options: ["False", "True", "0", "None"],
    expectedAnswers: ["False"],
    hint: "0 bernilai False",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_8",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: 'bool("hello")',
    options: ["True", "False", "hello", "error"],
    expectedAnswers: ["True"],
    hint: "String tidak kosong = True",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_9",
    prompt: "Apa output dari kode berikut?",
    code: "print(abs(-7))",
    options: ["7", "-7", "0", "error"],
    expectedAnswers: ["7"],
    hint: "abs() = nilai absolut",
    difficulty: 5,
    blockType: "t-shape",
  },
  {
    id: "l5_10",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "sorted([3, 1, 2])",
    options: ["[1, 2, 3]", "[3, 2, 1]", "[1, 3, 2]", "[3, 1, 2]"],
    expectedAnswers: ["[1, 2, 3]"],
    hint: "sorted() mengurutkan list",
    difficulty: 5,
    blockType: "t-shape",
  },
];
