import { Question } from "../types";

export const level2Questions: Question[] = [
  {
    id: "l2_1",
    prompt: "Manakah list angka 1 sampai 3 yang benar?",
    options: ["[1, 2, 3]", "(1, 2, 3)", "{1, 2, 3}", "[1, 2, 3, 4]"],
    expectedAnswers: ["[1, 2, 3]"],
    hint: "Gunakan kurung siku: [1, 2, 3]",
    difficulty: 2,
    blockType: "medium",
  },
  {
    id: "l2_2",
    prompt: "Apa elemen pertama dari list berikut?",
    code: "x = [10, 20, 30]\nprint(x[0])",
    options: ["10", "20", "30", "0"],
    expectedAnswers: ["10"],
    hint: "Index dimulai dari 0",
    difficulty: 2,
    blockType: "small",
  },
  {
    id: "l2_3",
    prompt: "Berapa panjang list berikut?",
    code: "len([5, 10, 15, 20])",
    options: ["4", "3", "5", "20"],
    expectedAnswers: ["4"],
    hint: "Hitung jumlah elemen",
    difficulty: 2,
    blockType: "medium",
  },
  {
    id: "l2_4",
    prompt: "Apa hasil dari operasi berikut?",
    code: "[1, 2] + [3, 4]",
    options: ["[1, 2, 3, 4]", "[4, 6]", "[[1,2],[3,4]]", "error"],
    expectedAnswers: ["[1, 2, 3, 4]"],
    hint: "List bisa digabung dengan +",
    difficulty: 2,
    blockType: "medium",
  },
  {
    id: "l2_5",
    prompt: "Apa elemen terakhir dari list berikut?",
    code: '["a", "b", "c"][-1]',
    options: ["c", "a", "b", "-1"],
    expectedAnswers: ["c"],
    hint: "Index -1 = elemen paling kanan",
    difficulty: 2,
    blockType: "small",
  },
  {
    id: "l2_6",
    prompt: "Manakah yang merupakan list kosong?",
    options: ["[]", "{}", "()", "None"],
    expectedAnswers: ["[]"],
    hint: "List kosong: []",
    difficulty: 2,
    blockType: "small",
  },
  {
    id: "l2_7",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "[1, 2, 3][1]",
    options: ["2", "1", "3", "error"],
    expectedAnswers: ["2"],
    hint: "Index 1 = elemen kedua",
    difficulty: 2,
    blockType: "small",
  },
  {
    id: "l2_8",
    prompt: "Manakah list string yang benar?",
    options: [
      '["python", "java"]',
      "[python, java]",
      '{"python", "java"}',
      "(python, java)",
    ],
    expectedAnswers: ['["python", "java"]'],
    hint: "List string dengan kutip dalam kurung siku",
    difficulty: 2,
    blockType: "medium",
  },
  {
    id: "l2_9",
    prompt: "Apa hasil dari operasi berikut?",
    code: "[0] * 3",
    options: ["[0, 0, 0]", "[0, 3]", "[3]", "error"],
    expectedAnswers: ["[0, 0, 0]"],
    hint: "List * angka = pengulangan",
    difficulty: 2,
    blockType: "medium",
  },
  {
    id: "l2_10",
    prompt: "Apa hasil dari slicing berikut?",
    code: "[1, 2, 3][:2]",
    options: ["[1, 2]", "[2, 3]", "[1, 2, 3]", "[1]"],
    expectedAnswers: ["[1, 2]"],
    hint: "Slicing [:2] ambil index 0 dan 1",
    difficulty: 2,
    blockType: "medium",
  },
];
