import { Question } from "../types";

export const level3Questions: Question[] = [
  {
    id: "l3_1",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: 'len("python")',
    options: ["6", "5", "7", "4"],
    expectedAnswers: ["6"],
    hint: "Hitung jumlah karakter",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_2",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "list(range(3))",
    options: ["[0, 1, 2]", "[1, 2, 3]", "[0, 1, 2, 3]", "[3]"],
    expectedAnswers: ["[0, 1, 2]"],
    hint: "range(3) = 0, 1, 2",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_3",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "len([10, 20, 30, 40])",
    options: ["4", "3", "40", "100"],
    expectedAnswers: ["4"],
    hint: "Hitung elemen dalam list",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_4",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "list(range(1, 5))",
    options: ["[1, 2, 3, 4]", "[1, 2, 3, 4, 5]", "[0, 1, 2, 3, 4]", "[5]"],
    expectedAnswers: ["[1, 2, 3, 4]"],
    hint: "range(1,5) mulai dari 1 sampai 4",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_5",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: 'len("abc") + len("de")',
    options: ["5", "4", "6", "3"],
    expectedAnswers: ["5"],
    hint: "3 + 2 = 5",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_6",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "list(range(0, 6, 2))",
    options: ["[0, 2, 4]", "[0, 1, 2, 3, 4, 5]", "[2, 4, 6]", "[0, 6, 2]"],
    expectedAnswers: ["[0, 2, 4]"],
    hint: "range dengan step 2",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_7",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "len(range(10))",
    options: ["10", "9", "11", "0"],
    expectedAnswers: ["10"],
    hint: "range(10) punya 10 elemen",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_8",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "len([])",
    options: ["0", "1", "None", "error"],
    expectedAnswers: ["0"],
    hint: "List kosong panjangnya 0",
    difficulty: 3,
    blockType: "small",
  },
  {
    id: "l3_9",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: "list(range(5, 8))",
    options: ["[5, 6, 7]", "[5, 6, 7, 8]", "[6, 7, 8]", "[5, 8]"],
    expectedAnswers: ["[5, 6, 7]"],
    hint: "range(5,8) = 5, 6, 7",
    difficulty: 3,
    blockType: "medium",
  },
  {
    id: "l3_10",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: 'len("Hello World")',
    options: ["11", "10", "12", "9"],
    expectedAnswers: ["11"],
    hint: "Spasi juga dihitung",
    difficulty: 3,
    blockType: "medium",
  },
];
