import { Question } from "../types";

export const level4Questions: Question[] = [
  {
    id: "l4_1",
    prompt: "Apa output dari kode berikut?",
    code: "for i in range(3):\n    print(i)",
    options: ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "1, 2"],
    expectedAnswers: ["0, 1, 2"],
    hint: "range(3) = 0, 1, 2",
    difficulty: 4,
    blockType: "large",
  },
  {
    id: "l4_2",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "sum(range(4))",
    options: ["6", "10", "4", "3"],
    expectedAnswers: ["6"],
    hint: "0+1+2+3 = 6",
    difficulty: 4,
    blockType: "large",
  },
  {
    id: "l4_3",
    prompt: "Apa output dari kode berikut?",
    code: 'for x in "hi":\n    print(x)',
    options: ["h, i", "hi", "h i", "error"],
    expectedAnswers: ["h, i"],
    hint: "Loop iterasi setiap karakter",
    difficulty: 4,
    blockType: "large",
  },
  {
    id: "l4_4",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "sum([1, 2, 3, 4])",
    options: ["10", "4", "24", "8"],
    expectedAnswers: ["10"],
    hint: "1+2+3+4 = 10",
    difficulty: 4,
    blockType: "large",
  },
  {
    id: "l4_5",
    prompt: "Apa output dari kode berikut?",
    code: "for i in range(1, 4):\n    print(i * 2)",
    options: ["2, 4, 6", "1, 2, 3", "2, 4, 6, 8", "0, 2, 4"],
    expectedAnswers: ["2, 4, 6"],
    hint: "1*2, 2*2, 3*2",
    difficulty: 4,
    blockType: "large",
  },
  {
    id: "l4_6",
    prompt: "Apa hasil dari list comprehension berikut?",
    code: "[x**2 for x in range(4)]",
    options: ["[0, 1, 4, 9]", "[1, 4, 9, 16]", "[0, 2, 4, 6]", "[0, 1, 2, 3]"],
    expectedAnswers: ["[0, 1, 4, 9]"],
    hint: "0², 1², 2², 3²",
    difficulty: 4,
    blockType: "l-shape",
  },
  {
    id: "l4_7",
    prompt: "Berapa panjang list hasil ekspresi berikut?",
    code: "[x for x in range(10) if x % 2 == 0]",
    options: ["5", "4", "10", "6"],
    expectedAnswers: ["5"],
    hint: "Bilangan genap 0-9: ada 5",
    difficulty: 4,
    blockType: "l-shape",
  },
  {
    id: "l4_8",
    prompt: "Apa output dari kode berikut?",
    code: 'for i in range(3):\n    print("*" * (i+1))',
    options: ["*, **, ***", "*, *, *", "***, **, *", "1, 2, 3"],
    expectedAnswers: ["*, **, ***"],
    hint: "1 bintang, 2 bintang, 3 bintang",
    difficulty: 4,
    blockType: "l-shape",
  },
  {
    id: "l4_9",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "sum(i for i in range(1, 6))",
    options: ["15", "21", "10", "6"],
    expectedAnswers: ["15"],
    hint: "1+2+3+4+5 = 15",
    difficulty: 4,
    blockType: "large",
  },
  {
    id: "l4_10",
    prompt: "Apa hasil dari ekspresi berikut?",
    code: '"".join([str(i) for i in range(4)])',
    options: ["0123", "0, 1, 2, 3", "123", "0 1 2 3"],
    expectedAnswers: ["0123"],
    hint: "Gabung 0,1,2,3 tanpa pemisah",
    difficulty: 4,
    blockType: "large",
  },
];
