import { Question } from "../types";

export const level1Questions: Question[] = [
  {
    id: "l1_1",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "2 + 3",
    options: ["5", "23", "6", "7"],
    expectedAnswers: ["5"],
    hint: "Cukup hitung 2 + 3",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_2",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "10 - 4",
    options: ["6", "14", "5", "4"],
    expectedAnswers: ["6"],
    hint: "Kurangi 10 dengan 4",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_3",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "3 * 4",
    options: ["12", "7", "34", "10"],
    expectedAnswers: ["12"],
    hint: "Kalikan 3 dan 4",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_4",
    prompt: "Apa output dari kode berikut?",
    code: 'print("hello")',
    options: ["hello", '"hello"', "print", "error"],
    expectedAnswers: ["hello"],
    hint: "print() menampilkan teks tanpa tanda kutip",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_5",
    prompt: "Apa tipe data dari 3.14?",
    code: "type(3.14)",
    options: ["float", "int", "str", "double"],
    expectedAnswers: ["float"],
    hint: "Angka desimal adalah float",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_6",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "10 // 3",
    options: ["3", "3.33", "4", "1"],
    expectedAnswers: ["3"],
    hint: "// adalah pembagian bilangan bulat",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_7",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "10 % 3",
    options: ["1", "3", "0", "10"],
    expectedAnswers: ["1"],
    hint: "% adalah sisa bagi (modulo)",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_8",
    prompt: "Apa tipe data dari 42?",
    code: "type(42)",
    options: ["int", "float", "str", "number"],
    expectedAnswers: ["int"],
    hint: "42 adalah integer",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_9",
    prompt: "Berapa hasil dari ekspresi berikut?",
    code: "2 ** 3",
    options: ["8", "6", "9", "5"],
    expectedAnswers: ["8"],
    hint: "** artinya pangkat. 2^3 = 8",
    difficulty: 1,
    blockType: "small",
  },
  {
    id: "l1_10",
    prompt: "Apa output dari kode berikut?",
    code: 'print("py" + "thon")',
    options: ["python", "py thon", "pythonpython", "error"],
    expectedAnswers: ["python"],
    hint: "String bisa digabung dengan +",
    difficulty: 1,
    blockType: "small",
  },
];
